### ISSUE TITLE
kcov is covering only one test case?

### ISSUE THREAD

**Issue by NetraPK** [particleflux/kcov-bats-circleci-codeclimate#1]
Hello,
I am trying to run code coverage for bats script. 

hello.bats:
#!/usr/bin/env bats

@test "hello without arguments" {
    result=$(bash $BATS_TEST_DIRNAME/../hello.sh)
    [[ "$result" == "Hello unknown" ]]
}

@test "hello with world argument" {
    result=$(bash $BATS_TEST_DIRNAME/../hello.sh world)
    [[ "$result" == "Hello World" ]]
}

hello.sh
#!/usr/bin/env bash

if [[ "$1" == "world" ]]; then
    echo "Hello World"
else
    echo "Hello unknown"
fi

Command I am executing:
kcov coverage/ tests/hello.bats

It is generating the coverage report but for only first test case which is "hello without arguments"

Can you help me?

<img width="730" alt="Screenshot 2021-12-07 at 2 58 51 PM" src="https://user-images.githubusercontent.com/89068241/145003057-ceaec1fb-320c-4679-853a-736fd5b1cadd.png">

**Comment by particleflux** [comment]
That's coverage of the tests, not of the actual code under test. 

Try `kcov --include-path=. coverage/ bats tests/` 

Note that it actually executes `bats`, and not the test file directly - the test directory/file is an argument to `bats`, not kcov.
Note also that the coverage reports includes a lot of non-related binaries, that's why the `--include-path=.` parameter filters it down to the current directory, where the script under test (`hello.sh`) resides.

**Comment by NetraPK** [comment]
Then I get an empty report?

This time I executed below commad:
kcov --include-path=. coverage/ /usr/local/bin/bats tests/


<img width="178
<img width="1626" alt="Screenshot 2021-12-08 at 10 35 30 AM" src="https://user-images.githubusercontent.com/89068241/145151401-24d7a660-8c3c-4a1a-9973-f1ecb2531bab.png">
<img width="1779" alt="Screenshot 2021-12-08 at 10 37 14 AM" src="https://user-images.githubusercontent.com/89068241/145151530-3fcca84f-6554-4fb6-8457-6c6791f4c1d3.png">

**Comment by particleflux** [comment]
Interesting. For me, it reports 100% on "bats", though if clicked it shows the actual script under test.

I know there are issues with running kcov in docker, maybe there are some incompatibilities with mac too?
(Linux here)

Interestingly enough, that output which you get, is the same as the failing one in docker, if I remember correctly.
Here, the command returns no output at all.

**Comment by NetraPK** [comment]
If possible can you please provide me the screenshots.

**Comment by NetraPK** [comment]
I launched and ec2 ubuntu machine install kcov and ran below command:
kcov coverage/ /usr/bin/bats tests/

and 

kcov --include-path=. coverage/ /usr/bin/bats tests/

after executing the command below is the output and in the report I can see any hello.sh file or hello.bats file.
<img width="1371" alt="Screenshot 2021-12-10 at 4 33 31 PM" src="https://user-images.githubusercontent.com/89068241/145564182-c06a187f-82a4-473a-a228-8483cdfa9a3b.png">

**Comment by NetraPK** [comment]
> Interesting. For me, it reports 100% on "bats", though if clicked it shows the actual script under test.
> 
> I know there are issues with running kcov in docker, maybe there are some incompatibilities with mac too? (Linux here)
> 
> Interestingly enough, that output which you get, is the same as the failing one in docker, if I remember correctly. Here, the command returns no output at all.

You mentioned that actual script is visible in code coverage did you mean hello.bats or hello.sh?
